### PREDICT IMAGE
POST http://localhost:8000/predict/image
content-type: application/json

{
    "image_id": "2402585",
    "url": "https://cs.stanford.edu/people/rak248/VG_100K/2367862.jpg",
    "local": false,
    "scene_element": 0,
    "extra_params": {
        "min_prob": 0.5
    }
}

### PREDICT IMAGES
POST http://localhost:8000/predict/images
content-type: application/json

{
    "images": [
        { "image_id": "2402585", "url": "https://cs.stanford.edu/people/rak248/VG_100K/2367862.jpg" },
        { "image_id": "2402585", "url": "https://cs.stanford.edu/people/rak248/VG_100K/2367862.jpg" }
    ],
    "output" : "json",
    "is_async": true,
    "extra_params": {
    }
}

### jobs
GET  http://localhost:8000/jobs

### specific job
GET  http://localhost:8000/jobs/45f4739b-146a-4ae3-9d06-16dee5df6ca7
### predict
POST http://localhost:8000/predict
content-type: application/json

{
    "movie_id": "Movies/308421",
    "local": false,
    "scene_element": 1,
    "extra_params": {
        "min_prob": 0.5
    }
}
